//! \file

#ifndef YACK_RANDOMIZED_BITS_INCLUDED
#define YACK_RANDOMIZED_BITS_INCLUDED 1

#include "yack/setup.hpp"
#include "yack/arith/base2.hpp"

namespace yack
{

    namespace randomized
    {
        //______________________________________________________________________
        //
        //
        //! bits interface
        //
        //______________________________________________________________________
        class bits
        {
        public:
            //__________________________________________________________________
            //
            // members
            //__________________________________________________________________
            const size_t count; //!< max number of genrated  bits
            const size_t bytes; //!< max number of generated bytes

            //__________________________________________________________________
            //
            // C++
            //__________________________________________________________________
            virtual ~bits() throw(); //!< cleanup

        protected:
            explicit bits(const size_t num_bits) throw(); //!< setup

        public:
            //__________________________________________________________________
            //
            // virtual interface
            //__________________________________________________________________
            virtual double operator()(void) throw() = 0; //!< uniform in ]0:1[

            //__________________________________________________________________
            //
            // non virtual interface
            //__________________________________________________________________
            size_t leq(const size_t value) throw();            //!< floor( ran() * value + 0.5 )
            bool   choice() throw();                           //!< ran <= 0.5
            unit_t in(const unit_t a, const unit_t b) throw(); //!< in [a:b]

            //! double|float|uint[8:16:32:64]_t
            template <typename T> T to() throw();

            //! double|float
            template <typename T> inline
            T symm() throw() {
                static const T half(0.5);
                const T d = (*this).to<T>()-half;
                return d+d;
            }
            
            //! bitwise full construction
            template <typename T> inline
            T full() throw()
            {
                T ans = 0;
                for(size_t i=sizeof(T)*8;i>0;--i)
                {
                    ans <<= 1;
                    if(choice()) ans |= 1;
                }
                return ans;
            }

            //! bitwise words of exactly nbit
            template <typename T> inline
            T gen(const size_t nbit) throw()
            {
                assert(nbit<=sizeof(T)*8);
                if(nbit>0)
                {
                    T ans = 1;
                    for(size_t i=nbit;i>1;--i)
                    {
                        ans <<= 1;
                        if(choice()) ans |= 1;
                    }
                    return ans;
                }
                else
                {
                    return T(0);
                }
            }


            //! fill with non zero bytes
            void fill(void *addr, size_t size) throw();


        private:
            YACK_DISABLE_COPY_AND_ASSIGN(bits);
        };


      



    }

}

#endif


