message( STATUS "cleaning temporary files" )
set(to_remove)

if(APPLE)
	message( STATUS "collecting .DS_Store...")
	file(GLOB_RECURSE ds_store ".DS_Store")
	list(APPEND to_remove ${ds_store})
endif()

macro(remove_pattern p)
	message( STATUS "collecting '${p}'..." )
	file(GLOB tmp ${p})
	list(APPEND to_remove ${tmp})	
endmacro()

remove_pattern(*.dat)
remove_pattern(*.dot)
remove_pattern(*.png)
remove_pattern(*.bin)
remove_pattern(algo/*.aux)
remove_pattern(algo/*.log)
remove_pattern(algo/*.synctex.gz)

foreach(f IN LISTS to_remove )
	message( STATUS "removing ${f}" )
	execute_process(COMMAND ${CMAKE_COMMAND} -E rm -f ${f})
endforeach()
